In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [ ]:
data = pd.read_excel("Data2021_3.xlsx")
data.dropna()
print(data.shape)
print(data.columns)

(80000, 29)
Index(['Unnamed: 0', 'A_AGE', 'A_HGA', 'A_MARITL', 'A_FAMREL', 'A_SEX',
       'P_STAT', 'PECERT1', 'PECERT2', 'PECERT3', 'A_HRSPAY', 'A_HRLYWK',
       'A_WKSTAT', 'CLWK', 'EARNER', 'PHMEMPRS', 'ERN_SRCE', 'CAP_VAL',
       'WSAL_YN', 'FILESTAT', 'TAX_INC', 'A_CLSWKR', 'A_FAMREL.1', 'PRDTRACE',
       'A_SEX.1', 'CAP_VAL.1', 'A_USLHRS', 'PRCITSHP', 'PTOT_R'],
      dtype='object')


In [ ]:
data1 = data.copy()

In [ ]:
data1['PTOT_R'] = np.where(np.logical_and(data1['PTOT_R'] >=0,data1['PTOT_R'] <17) , 1, data1['PTOT_R'])
data1['PTOT_R'] = np.where(np.logical_and(data1['PTOT_R'] >=17,data1['PTOT_R'] <26) , 2, data1['PTOT_R'])
data1['PTOT_R'] = np.where(data1['PTOT_R'] >=26, 3, data1['PTOT_R'])

In [ ]:
data1['A_AGE'] = np.where(np.logical_and(data1['A_AGE'] >=1,data1['A_AGE'] <19) , 1, data1['A_AGE'])
data1['A_AGE'] = np.where(np.logical_and(data1['A_AGE'] >=19,data1['A_AGE'] <=30) , 2, data1['A_AGE'])
data1['A_AGE'] = np.where(np.logical_and(data1['A_AGE'] >=31,data1['A_AGE'] <=50) , 3, data1['A_AGE'])
data1['A_AGE'] = np.where(data1['A_AGE'] >50 , 4, data1['A_AGE'])

In [ ]:
data1['A_HGA'] = np.where(data1['A_HGA']>30,data1['A_HGA']-30,data1['A_HGA'])

In [ ]:
data1['A_HRSPAY'] = np.where(data1['A_HRSPAY'] > 0 ,data1['A_HRSPAY']/100 , data1['A_HRSPAY'])
data1['A_HRSPAY'] = np.where(data1['A_HRSPAY'] < 0 ,0 , data1['A_HRSPAY'])

In [ ]:
data1['PECERT1'] = np.where(data1['PECERT1'] < 0 ,0 , data1['PECERT1'])
data1['PECERT2'] = np.where(data1['PECERT2'] < 0 ,0 , data1['PECERT2'])
data1['PECERT3'] = np.where(data1['PECERT3'] < 0 ,0 , data1['PECERT3'])

In [ ]:
data1['A_USLHRS'] = np.where(data1['A_USLHRS'] == -4 , 20 , data1['A_USLHRS'])
data1['A_USLHRS'] = np.where(data1['A_USLHRS'] == -1 , 0 , data1['A_USLHRS'])

In [ ]:
#data1 = data1.drop('PTOTVAL',axis=1)
#data1 = data1.drop('A_FNLWGT',axis=1)
data1 = data1.drop('Unnamed: 0',axis=1)


In [ ]:
X = data1.loc[:, data1.columns != 'PTOT_R']
y = data1.loc[:, data1.columns == 'PTOT_R']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
columns = X_train.columns

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
rfe = RFE(logreg, n_features_to_select=10)
rfe = rfe.fit(X_train, y_train.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[ True  True False False  True  True False False  True False False  True
 False  True False  True False  True False False False False False  True
 False False False]
[ 1  1  5  7  1  1 10 11  1 15  2  1  6  1  3  1 16  1 13 17  9  4 12  1
 18 14  8]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
data1

A_AGE  A_HGA  A_MARITL  A_FAMREL  ...  CAP_VAL.1  A_USLHRS  PRCITSHP  PTOT_R
0          4     12         7         0  ...          0         0         1       2
1          3     11         1         1  ...          0        20         1       1
2          4     14         1         2  ...          0        40         1       3
3          1      0         7         3  ...          0         0         1       1
4          1      0         7         3  ...          0         0         1       1
...      ...    ...       ...       ...  ...        ...       ...       ...     ...
79995      2     10         7         3  ...          0        20         1       1
79996      2     10         7         3  ...          0        20         1       1
79997      1      0         7         3  ...          0         0         1       1
79998      4      9         5         1  ...          0         0         1       1
79999      4      9         5         4  ...          0         0         1       1

[80000 rows x 27 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X = data1.loc[:, data1.columns != 'PTOT_R']
y = data1.loc[:, data1.columns == 'PTOT_R']

In [ ]:
cols = X.columns
new_cols = []
for i,j in enumerate(rfe.ranking_):
  if(j<7):
    new_cols.append(cols[i])
  else:
    print(cols[i])
X = X[new_cols]
print(X)
print(new_cols)

A_FAMREL
PECERT1
PECERT2
A_HRSPAY
CAP_VAL
FILESTAT
TAX_INC
A_CLSWKR
PRDTRACE
CAP_VAL.1
A_USLHRS
PRCITSHP
       A_AGE  A_HGA  A_MARITL  A_SEX  ...  ERN_SRCE  WSAL_YN  A_FAMREL.1  A_SEX.1
0          4      9         1      2  ...         0        2           1        2
1          4      9         1      1  ...         1        1           2        1
2          4      9         4      2  ...         0        2           4        2
3          4     13         1      2  ...         1        1           1        2
4          4      9         1      1  ...         1        1           2        1
...      ...    ...       ...    ...  ...       ...      ...         ...      ...
79995      3      9         1      1  ...         1        1           2        1
79996      1      0         7      1  ...         0        0           3        1
79997      3     13         5      2  ...         1        1           1        2
79998      1      5         7      2  ...         0        2           3   

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.15, random_state=0)
#columns = X_train.columns
logreg = LogisticRegression(multi_class='multinomial', solver='lbfgs')
logreg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(multi_class='multinomial')

In [ ]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.77


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[7381    1  559    0]
 [ 821    0  625    0]
 [ 643    3 1762    0]
 [  98    0  107    0]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.83      0.93      0.88      7941
           2       0.28      0.01      0.02      1651
           3       0.59      0.75      0.66      2408

    accuracy                           0.77     12000
   macro avg       0.57      0.56      0.52     12000
weighted avg       0.71      0.77      0.72     12000



In [ ]:
# print(logreg.predict([].reshape(1,-1)))
print(y_pred[6])

1


In [ ]:
X_test[6]

array([-0.5483476 ,  0.94586516,  0.9760112 ,  1.91638465,  0.97143287,
       -0.51747315,  0.68370758, -0.38111636, -0.35013189, -0.17521221,
       -0.32560684,  3.32968346, -0.53777041, -0.10463609,  0.69771577,
        0.81317791, -0.04262383, -0.13821612,  0.57935478, -0.35756177,
        0.08535209,  1.91638465, -0.37923228,  0.97143287, -0.04262383,
       -0.85297271, -0.37140844])

In [ ]:
data = pd.read_excel("Data2018_1.xlsx")
data.dropna()
print(data.shape)
print(data.columns)

(30000, 14)
Index(['Unnamed: 0', 'A_AGE', 'A_FNLWGT', 'A_HGA', 'A_MARITL', 'A_CLSWKR',
       'A_FAMREL', 'PRDTRACE', 'A_SEX', 'CAP_VAL', 'A_USLHRS', 'PRCITSHP',
       'PTOTVAL', 'PTOT_R'],
      dtype='object')


In [ ]:
data1 = data.copy()
data1 = data1.drop('Unnamed: 0',axis=1)
data1 = data1.drop('PTOTVAL',axis=1)

In [ ]:
data1['PTOT_R'] = np.where(np.logical_and(data1['PTOT_R'] >=1,data1['PTOT_R'] <5) , 1, data1['PTOT_R'])
data1['PTOT_R'] = np.where(np.logical_and(data1['PTOT_R'] >=5,data1['PTOT_R'] <20) , 2, data1['PTOT_R'])
data1['PTOT_R'] = np.where(np.logical_and(data1['PTOT_R'] >=20, data1['PTOT_R'] <41) , 3, data1['PTOT_R'])
data1['PTOT_R'] = np.where(data1['PTOT_R'] >=41, 4, data1['PTOT_R'])

In [ ]:
X = data1.loc[:, data1.columns != 'PTOT_R']
y = data1.loc[:, data1.columns == 'PTOT_R']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
columns = X_train.columns
logreg = LogisticRegression(multi_class='multinomial', solver='lbfgs')
logreg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(multi_class='multinomial')

In [ ]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

NotFittedError: ignored

In [ ]:
data1

A_AGE  A_HGA  A_MARITL  A_FAMREL  ...  CAP_VAL.1  A_USLHRS  PRCITSHP  PTOT_R
0          1     12         7         0  ...          0         0         1       2
1          1     11         1         1  ...          0        20         1       1
2          1     14         1         2  ...          0        40         1       3
3          1      0         7         3  ...          0         0         1       1
4          1      0         7         3  ...          0         0         1       1
...      ...    ...       ...       ...  ...        ...       ...       ...     ...
79995      1     10         7         3  ...          0        20         1       1
79996      1     10         7         3  ...          0        20         1       1
79997      1      0         7         3  ...          0         0         1       1
79998      1      9         5         1  ...          0         0         1       1
79999      1      9         5         4  ...          0         0         1       1

[80000 rows x 27 columns]